title: MyBlog
email: Suvd037@kookmin.ac.kr
description: >- 
baseurl: "" 
url: "https://github.com/Sumi037/Sumi037.github.io"
github_username: Sumi037


theme: jekyll-theme-architect
plugins:
  - jekyll-feed